#include "SerPrunesALotWindow.h"
#include <QtWidgets/QApplication>

/**
* Code automatically generated by the ''New Project -> Qt Application'' wizard
*/

int main(int argc, char *argv[])
{
	QApplication application(argc, argv);
	SerPrunesALotWindow window;
	window.show();
	window.updateGui();
	return application.exec();
}
