#pragma once

#include <vector>

#include <QtWidgets/QMainWindow>
#include <qlabel>
#include "QAction.h"

#include "AiEngine.h"
#include "GameBoardButton.h"
#include "GameConstants.h"
#include "GameState.h"
#include "ui_SerPrunesALot.h"

/**
 * The application's main window.
 *
 * Code initially generated by the ''New Project -> Qt Application'' wizard,
 * afterwards edited to add new methods and fields.
 */
class SerPrunesALotWindow : public QMainWindow
{
	Q_OBJECT

public:
	SerPrunesALotWindow(QWidget *parent = 0);
	~SerPrunesALotWindow();

	/** Informs the window that a certain button has been clicked */
	void buttonClicked(GameBoardButton* button);

	/** 
	 * Initializes the board, meaning that the board reverts to the game's initial state.
	 * Can also be used to reset.
	 */
	void initBoard();

	/** Highlights ALL locations on the board that can be moved to this turn */
	void highlightAllMoves();

	/** Tells the AI engine to play this turn */
	void playTurnAi();

	/** Sets the Black Player's AI engine to whatever button is chosen in the menu */
	void resetBlackAiEngine();
	/** Sets the White Player's AI engine to whatever button is chosen in the menu */
	void resetWhiteAiEngine();

	/** Reverts the game state back to the way it was before executing the last executed move */
	void undoLastMove();

	/** Updates the GUI, in order to show the currentGameState again */
	void updateGui();

protected:
	/** Event called right after the window has been resized, and before window is painted again */
	virtual void resizeEvent(QResizeEvent* event);

private:
	/** Matrix of all the buttons on the board */
	std::vector<std::vector<GameBoardButton*>> boardButtons;
	/** Vector of icons which are currently highlighted as being possible to move to */
	std::vector<GameBoardButton*> highlightedButtons;
	/** Sequence of moves that have been played in the past */
	std::vector<Move> movesPlayed;
	/** The current game state shown by the GUI */
	GameState currentGameState;
	/** The button that is currently selected */
	GameBoardButton* selectedButton;

	/** Something UI-related. This member was generated by the Qt Application wizard */
	Ui::SerPrunesALotClass ui;

	/** The AI engine currently being used by the Black Player */
	AiEngine* aiEngineBlack;
	/** The AI engine currently being used by the White Player */
	AiEngine* aiEngineWhite;

	// Menu options
	/** Option to toggle if AI control of the black player is allowed */
	QAction* blackPlayerAiControl;
	/** Option to toggle if manual control of the black player is allowed */
	QAction* blackPlayerManualControl;
	/** Option to toggle if AI control of the white player is allowed */
	QAction* whitePlayerAiControl;
	/** Option to toggle if manual control of the black player is allowed */
	QAction* whitePlayerManualControl;

	/** If toggled, Black Player will use Basic Alpha Beta engine */
	QAction* blackPlayerBasicAlphaBeta;
	/** If toggled, Black Player will use Alpha Beta with Transposition Table */
	QAction* blackPlayerAlphaBetaTT;
	/** If toggled, White Player will use Basic Alpha Beta engine */
	QAction* whitePlayerBasicAlphaBeta;
	/** If toggled, White Player will use Alpha Beta with Transposition Table */
	QAction* whitePlayerAlphaBetaTT;

	// Status Bar
	/** The label in the status bar that will tell the user when an AI engine has detected a win or a loss */
	QLabel* winDetectionLabel;
};
